name: Wild
version: 1.0.17-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.wild.Wild
description:
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  wild:
    description: Teleports to a random location that is safe.
permissions:
  wild.*:
    default: op
    children:
      wild.use: true
      wild.nocooldown: true
  wild.use:
    default: true
  wild.nocooldown:
    default: op
